myHabr/faq/urls.py
from django.urls import path

from .views import home, single
urlpatterns = [
    path('', home, name='faq'),
    path('<int:id>/', single, name='single'),
]

myHabr/myHabr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blogapp
from blogapp.views import Category, AllBlogsListView
from mainapp import views as mainapp
from mainapp.views import BlogAddCommentLike, BlogAddLike, BlogAddDislike, BlogAddCommentDislike
from feeds import LatestPostsFeed

urlpatterns = [
    path(r'admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
    path('', mainapp.BlogListView.as_view(), name='index'),
    path('faq/', include('faq.urls')),
    path('myblogs/', include('blogapp.urls', namespace='blogapp')),
    path('allblogs/', AllBlogsListView.as_view(), name='allblogs'),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('blog/', mainapp.BlogPostView.as_view(), name='blogpost'),
    path('blog/<int:pk>', mainapp.BlogPostDetail.as_view(), name='blogpost_detail'),
    path('blog/<int:pk>/edit/', mainapp.BlogPostUpdate.as_view(), name='blogpost_update'),
    path('blog/create/new/', mainapp.BlogPostCreate.as_view(), name='blogpost_create'),
    path('blog/<int:pk>/delete/', mainapp.BlogPostDelete.as_view(), name='blogpost_delete'),
    path('blog/<int:pk>/verify/', mainapp.send_under_review, name='send_under_review'),
    path('blog/<int:pk>/private/', mainapp.BlogPostPrivateDetail.as_view(), name='blogpost_detail-private'),
    path('blog/comment/', mainapp.blog_comment, name='blog_comment'),
    path('blog/sub_comment/', mainapp.blog_sub_comment, name='blog_sub_comment'),
    path('blog/comment_edit/', mainapp.blog_comment_edit, name='blog_comment_edit'),
    path('delete_comment/', mainapp.delete_comment, name='delete_comment'),
    path('blog/comment/<int:pk>/like/', BlogAddCommentLike.as_view(), name='comment-like'),
    path('blog/comment/<int:pk>/dislike/', BlogAddCommentDislike.as_view(), name='comment-dislike'),
    path('blog/<int:pk>/like/', BlogAddLike.as_view(), name='like'),
    path('blog/<int:pk>/dislike/', BlogAddDislike.as_view(), name='dislike'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('mark_read/', mainapp.mark_read, name='mark_read'),
    path('message_count/', mainapp.message_count, name='message_count'),
    path('category/<int:pk>/', Category.as_view(), name='category'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('call_moderator/', mainapp.call_moderator, name='cal_moderator'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myHabr/profiles/urls.py
from django.urls import path
from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('<int:id_profile>/<int:user>/', views.profile, name='profile'),
    # path('create_profile/<int:id>/', views.create_profile, name='create'),
    path('create_update_profile/<int:id>/', views.update_profile, name='update'),
    # path('like/<int:id>/', views.like, name='like')
    path('like/<int:who_id>/<int:whom_id>/', views.profile_like, name='like'),
    path('dislike/<int:who_id>/<int:whom_id>/', views.profile_dislike, name='dislike'),
]

myHabr/mainapp/forms.py
from django import forms
from .models import BlogPost, Tag, Blogs


class BlogPostForm(forms.ModelForm):
    """Данная форма работает только с подключенным бутстрапом"""

    def save(self, commit=True):
        instance = super().save()
        if not instance.tag_list:
            return instance
        tags = instance.tag_list.split()
        if tags:
            for tag in tags:
                if not tag:
                    continue
                tag, _ = Tag.objects.get_or_create(name=tag)
                instance.tags.add(tag)
        if commit:
            instance.save()
        return instance

    class Meta:
        model = BlogPost

        fields = ('title', 'blog', 'image_header', 'body', 'tag_list')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'blog': forms.Select(attrs={'class': 'form-control'}),
            'image_header': forms.FileInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'tag_list': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(BlogPostForm, self).__init__(*args, **kwargs)
        blogs = Blogs.objects.filter(user=self.initial['user'])
        self.fields['blog'].queryset = blogs

myHabr/mainapp/views.py
import json
from operator import itemgetter

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from adminapp.models import Message
from mainapp.models import BlogPost, Comment
from mainapp.utils import (create_comment_like_message,
                           create_post_like_message, find_article_by_comment)
from .forms import BlogPostForm
from .models import CommentsLink


class BlogListView(ListView):
    """[M] На главной странице должны подряд отображаться последние
    публикации, вне зависимости от тематики, отсортированные по дате
    (сначала самые свежие)"""
    model = BlogPost
    template_name = 'mainapp/index.html'
    paginate_by = 3

    def get_queryset(self):
        return BlogPost.objects.order_by('-create_date').filter(status__in=BlogPost.PUBLISHED)

    def post(self, request, *args, **kwargs):
        blogs = BlogPost.objects.order_by('-create_date').filter(status__in=BlogPost.PUBLISHED)
        if self.request.POST.get('pk') == '0':
            new_blogs = [[(blog.likes.count() - blog.dislikes.count()), blog] for blog in blogs]
            new_blogs = sorted(new_blogs, key=itemgetter(0), reverse=True)
            blogs = []
            for i in new_blogs:
                blogs.append(i[1])

        context = {
            'object_list': blogs
        }
        return render(request=request, template_name='mainapp/index.html', context=context)


class BlogPostView(ListView):
    model = BlogPost
    template_name = "blogpost.html"

    def get_queryset(self):
        user = self.request.user
        return BlogPost.objects.filter(author=user).exclude(status="0").order_by('-create_date')


class BlogPostDetail(DetailView):
    """Для отображения всем пользователям"""
    model = BlogPost
    template_name = "blogpost/blogpost-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context_related = BlogPost.objects.filter(blog=self.object.blog, status='3').exclude(pk=self.object.pk)[:3]

        comments = Comment.objects \
            .filter(commentslink__type='article',
                    commentslink__assigned_id=self.object.id) \
            .prefetch_related('user')

        for comment in comments:
            comment.find_children()

        context['related'] = context_related
        context['comments'] = comments
        context['post'] = BlogPost.objects.filter(pk=self.object.pk)

        return context


class BlogPostPrivateDetail(DetailView):
    """Для отображения в личном кабинете пользователя"""
    model = BlogPost
    template_name = "blogpost/blogpost-detail-private.html"


def send_under_review(request, pk):
    """функция для перевода статуса блога из 'черновик' в 'статья на проверке' """
    obj = get_object_or_404(BlogPost, pk=pk)
    obj.status = BlogPost.UNDER_REVIEW
    obj.save()
    info = (obj._meta.app_label, obj._meta.model_name)
    admin_url = reverse('admin:%s_%s_change' % info, args=(obj.pk,))
    admin_url = request.build_absolute_uri(admin_url)
    # исключение для того, чтобы работало fill_db
    try:
        Message.objects.get_or_create(
            from_user=obj.author,
            to_group=Group.objects.get(name='moderator'),
            text=admin_url,
            type_message='1',
            url=admin_url
        )
    except:
        pass
    return redirect(request.META['HTTP_REFERER'])


class BlogPostCreate(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "blogpost/blogpost_form.html"
    success_url = reverse_lazy("blogpost")

    def get_initial(self):
        user = self.request.user.id
        self.initial = {"user": user}
        return self.initial

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogPostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "blogpost/blogpost_update.html"
    success_url = reverse_lazy("blogpost")

    def get_initial(self):
        user = self.request.user.id
        self.initial = {"user": user}
        return self.initial

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class BlogPostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = BlogPost
    template_name = "blogpost/blogpost_delete.html"
    success_url = reverse_lazy("blogpost")

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class BlogAddLike(LoginRequiredMixin, View):
    """
    [M] Как зарегистрированный пользователь
    я хочу ставить один лайк или дизлайк к любой статье,
    чтобы составить свое мнение о статье
    """

    def post(self, request, pk, *args, **kwargs):
        post = BlogPost.objects.get(pk=pk)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)
            create_post_like_message(post,request, is_like=True)

        if is_like:
            post.likes.remove(request.user)

        sum_rating = post.likes.all().count() - post.dislikes.all().count()

        return HttpResponse(
            json.dumps({
                'like_count': post.likes.all().count(),
                'dislike_count': post.dislikes.all().count(),
                'sum_rating': sum_rating,
            }),
            content_type='application/json'
        )


class BlogAddDislike(LoginRequiredMixin, View):
    """
    [M] Как зарегистрированный пользователь
    я хочу ставить один лайк или дизлайк к любой статье,
    чтобы составить свое мнение о статье
    """

    def post(self, request, pk, *args, **kwargs):
        post = BlogPost.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)
            create_post_like_message(post, request, is_like=False)

        if is_dislike:
            post.dislikes.remove(request.user)

        sum_rating = post.likes.all().count() - post.dislikes.all().count()

        return HttpResponse(
            json.dumps({
                'like_count': post.likes.all().count(),
                'dislike_count': post.dislikes.all().count(),
                'sum_rating': sum_rating,
            }),
            content_type='application/json'
        )


@method_decorator(csrf_exempt, name='post')
@method_decorator(csrf_exempt, name='dispatch')
class BlogAddCommentLike(LoginRequiredMixin, View):
    """
    [M] Как зарегистрированный пользователь я хочу ставить
    один лайк или дизлайк к любому зарегистрированному пользователю,
    чтобы составить свое мнение о том, что написал пользователь
    """

    def post(self, request, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)

        is_dislike = False

        for dislike in comment.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            comment.dislikes.remove(request.user)

        is_like = False

        for like in comment.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            comment.likes.add(request.user)
            create_comment_like_message(comment, request, is_like=True)

        if is_like:
            comment.likes.remove(request.user)

        sum_rating_comments = comment.likes.all().count() - comment.dislikes.all().count()

        return HttpResponse(
            json.dumps({
                'comment_like_count': comment.likes.all().count(),
                'comment_dislike_count': comment.dislikes.all().count(),
                'sum_rating_comments': sum_rating_comments,
            }),
            content_type='application/json'
        )


@method_decorator(csrf_exempt, name='post')
@method_decorator(csrf_exempt, name='dispatch')
class BlogAddCommentDislike(LoginRequiredMixin, View):
    """
    [M] Как зарегистрированный пользователь я хочу ставить
    один лайк или дизлайк к любому зарегистрированному пользователю,
    чтобы составить свое мнение о том, что написал пользователь
    """

    def post(self, request, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)

        is_like = False

        for like in comment.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            comment.likes.remove(request.user)

        is_dislike = False

        for dislike in comment.dislikes.all():
            if dislike == request.user:

myHabr/mainapp/templates/blogpost/blogpost-detail-private.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} {{ object.title }} - MyHabr {% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ object.title }}</h1>
        <h2>Автор: {{ object.author }}</h2></br>
        <hr>
        </br>
        <img src="{{ object.image_header.url }}"
             class="img-fluid"
             width="820"><br/>
        {{ object.body|safe }}<br/>
        <hr>
        </br>
      <a href="{% url 'blogpost_update' object.pk %}" type="button"> Редактировать статью </a></br>
        {% if object.status == "1" %}
            <button><a href="{% url 'send_under_review' object.pk %}"> Согласовать публикацию </a></button></br>
        {% elif object.status == "2" %}
            <button disabled>На модерации</button></br>
        {% endif %}
        <a href="{% url 'blogpost_detail' object.pk %}"> Показать публичную страницу </a></br>
        <a href="#" type="button" onclick="history.back();"> Назад </a></br>

        </br>
        </br>

    </div>
{% endblock %}

myHabr/mainapp/templates/blogpost/blogpost-detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
        {{ object.title }} - MyHabr
{% endblock %}
{% block css %}
    {{ block.super }}
    <style>
        a:hover {
            text-decoration: none;
        }

        .btn, .form-control {
            outline: none;
            -webkit-box-shadow: none !important;
            box-shadow: none !important;
            border-radius: 0;
        }

        .comment-body textarea {
            margin-bottom: 1em;
        }

        .children {
            padding-top: 1em !important;
            padding-bottom: 0 !important;
            margin-bottom: 1em !important;
        }

        .comment-list li {
            margin-bottom: 1em;
        }

        .call_button {
            border: none;
            background-color: white;
            transition: transform .25s;
            display: inline-block;
        }

        .call_button:hover {
            transform: scale(1.2);
            cursor: pointer;
        }

        .call_button:focus {
            outline: none;
        }

        .call_button .tooltiptext {
            visibility: hidden;
            width: 80px;
            background-color: grey;
            opacity: 0.5;
            text-align: center;
            padding: 1px 0;
            border-radius: 3px;
            position: absolute;
            z-index: 1;
            margin-left: 20px;
        }

        .call_button:hover .tooltiptext {
            visibility: visible;
        }

        .delete_message_button {
            border: none;
            background-color: white;
            transition: transform .25s;
            display: inline-block;
        }

        .delete_message_button:hover {
            transform: scale(1.2);
            cursor: pointer;
        }

        .delete_message_button:focus {
            outline: none;
        }

        .delete_message_button {
            font-size: 1.3rem;
            color: red;
        }

        #message {
            background-color: lightgreen;
            padding: 1em;
            position:fixed;
            opacity: 0.8;
            top:0;
            max-width:100%;
            z-index:100;
            display: none;
        }
        #message_button {
            display: inline-block;
            transition: transform .25s;
        }

        #message_button:hover {
            transform: scale(1.2);
            cursor: pointer;
        }
        #message_button:focus {
            outline: none;
        }

        .ui-autocomplete {
            background-color: white;
            border: solid #4ac1f7;
            max-width: 300px;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div id="message">Сообщение модератору отправлено <span id="message_button" style="color: red" onclick="hide_message(event)">X</span></div>
        <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
                <h1>{{ object.title }} ({{ object.blog }} ({{ object.blog.category }}))</h1>
                {% if user.id %}
                <h2>Автор:<a href="{% url 'profiles:profile'  object.author.id user.id %}">{{ object.author }}</a> </h2></br>
                {% else %}
                <h2>Автор:<a href="{% url 'profiles:profile'  object.author.id 0 %}">{{ object.author }}</a> </h2></br>
                {% endif %}
                <img src="{{ object.image_header.url }}"
                     class="img-fluid"
                     width="820"><br/>
                </br>
                {{ object.body|safe }}
                <hr>
                </br>
                {% if related %}
                    <div class="container relared">
                        ЧИТАЙТЕ ПОХОЖЕЕ </br>
                        {% for obj in related %}
                            <a href="{% url 'blogpost_detail' obj.pk %}">'{{ obj.title }}'</a><<  читать далее </br>
                            {{ obj.create_date }}  </br></br>
                        {% endfor %}
                    </div>
                {% endif %}
                </br>
                {% if user.is_authenticated %}
                    <a href="{% url 'blogpost' %}"> НАЗАД </a><br>
                {% else %}
                    <a href="#" type="button" onclick="history.back();"> НАЗАД </a>
                {% endif %}
                <hr>
                </br>
                <h3 class="mb-5">Комментарии</h3>
                {% include 'comments/comments.html' %}
                {% if user.is_authenticated %}
                    <h3 class="mb-1">Оставить комментарий:</h3>
                    <div class="comment-form-wrap pt-5">
                        <form id="comment_form" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="comment_text">Ваш комментарий:</label>
                                <textarea name="comment_text" class="form-control" id="comment_text"
                                          rows="4"></textarea>
                            </div>
                            <button id="comment_send" type="submit" class="btn btn-primary">Комментировать</button>
                        </form>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                <div class="sidebar-box">
                    <h3 class="heading">Тэги</h3>
                    <ul class="tags">
                        {% for tag in object.tags.all %}
                            <li><a href="#">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        let form = $('#comment_form');
        let send_comment = $('#comment_send');
        form.on('submit', function (event) {
            event.preventDefault();
            create_post();
        });

        function create_post() {
            var comment_text = $('[name="comment_text"]').val();
            $.ajax({
                url: "/blog/comment/", // the endpoint
                type: "POST", // http method
                data: {
                    comment_text: comment_text,
                    blog_id: {{ object.pk }},
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (json) {
                    $('.comment-list').replaceWith(json.comments);
                    $('[name="comment_text"]').val('');

                },
                error: function (xhr, errmsg, err) {
                    console.log('error');
                }
            })
        }

        function sub_comment(e) {
            e.preventDefault();
            let subcomment = $(e.target).parent();
            let comment_id = subcomment.attr('id');
            let subcomment_text = subcomment.find('textarea').first();
            if (subcomment_text.is(":hidden")) {
                subcomment_text.attr("hidden", false);
            } else {
                let comment_text = subcomment_text.val()
                $.ajax({
                        url: "/blog/sub_comment/",
                        type: "POST",
                        data: {
                            comment_text: comment_text,
                            comment_id: comment_id,
                            blog_id: {{ object.pk }},
                            csrfmiddlewaretoken: '{{ csrf_token }}',
                        },
                        success: function (json) {
                            $(e.target).parent().next('.children').html(json.comment)
                        },
                        error: function (xhr, errmsg, err) {
                            console.log('error');
                        }
                    }
                )
                subcomment_text.attr("hidden", true);
                subcomment_text.val('');
            }
        }

        function edit_comment(e) {
            e.preventDefault();
            let subcomment = $(e.target).parent();
            let comment_id = subcomment.attr('id');
            let reply_button = subcomment.find('.reply').first();
            let subcomment_text = subcomment.find('textarea').first();
            let previous_text = subcomment.find('p').text();
            if (subcomment_text.is(":hidden")) {
                subcomment_text.val(previous_text);
                subcomment_text.attr("hidden", false);
                reply_button.attr("hidden", true);
            } else {
                console.log(subcomment_text.val())
                $.ajax({
                        url: "/blog/comment_edit/",
                        type: "POST",
                        data: {
                            comment_text: subcomment_text.val(),
                            comment_id: comment_id,
                            blog_id: {{ object.pk }},
                            csrfmiddlewaretoken: '{{ csrf_token }}',
                        },
                        success: function (json) {
                            console.log(json.new_text);
                            subcomment.find('p').html(json.new_text + '<br>' + '<i>отредактировано ' + json.edited_at + '</i>')
                        },
                        error: function (xhr, errmsg, err) {
                            console.log('error');
                        }
                    }
                )
                subcomment_text.val('');
                subcomment_text.attr("hidden", true);
                reply_button.attr("hidden", false);
            }
        }

        function call_moderator(comment_id) {
            $('#message').show()
                $.ajax({
                        url: "/call_moderator/",
                        type: "POST",
                        data: {
                            comment_id: comment_id,
                            url: window.location.toString(),
                            csrfmiddlewaretoken: '{{ csrf_token }}',
                        },
                        success: function (json) {
                            console.log(json.success)
                            $('#message').show()
                        },
                        error: function (xhr, errmsg, err) {
                            console.log('error');
                        }
                    }
                )
            }

        function delete_comment(comment_id) {
            $.ajax({
                    url: "/delete_comment/",
                    type: "POST",
                    data: {
                        comment_id: comment_id,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (json) {
                        console.log(json.success);
                        $(`#${comment_id}`).closest('.row.comment').remove()
                    },
                    error: function (xhr, errmsg, err) {
                        console.log('error');
                    }
                }
            )
        }


        function hide_message(event) {
            $('#message').hide()
        }

      $( function() {
        var availableTags = ["@moderator"];
        $("#comment_text, [name='subcomment_text']").autocomplete({
          source: availableTags,
          position: {
                       my: "left",
                       at: "left center"
                    }
        });
      } );

    $( document ).ready(function() {
        $(document).on('submit', '.comment-like-form', function(e){
            e.preventDefault()
            const event_id = $(this).attr('id')
            const url = $(this).attr('action')
            console.log(event_id);
            console.log(url);
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'event_id':event_id,
                },
                success: function(response) {
                     $(`.comment-dislike-${event_id}`).text(response.comment_dislike_count)
                     $(`.comment-like-${event_id}`).text(response.comment_like_count)
                     $(`.comment-vote-${event_id}`).text(response.sum_rating_comments)
                },
                error: function(response) {
                    console.log('error', response)
                }
            })
        })
        $(document).on('submit', '.comment-dislike-form', function(e){
            e.preventDefault()
            const event_id = $(this).attr('id')
            const url = $(this).attr('action')
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'event_id':event_id,
                },
                success: function(response) {
                     $(`.comment-dislike-${event_id}`).text(response.comment_dislike_count)
                     $(`.comment-like-${event_id}`).text(response.comment_like_count)
                     $(`.comment-vote-${event_id}`).text(response.sum_rating_comments)
                },
                error: function(response) {
                    console.log('error', response)
                }
            })
        })
    });


    </script>
{% endblock %}

myHabr/mainapp/templates/blogpost/blogpost_delete.html
{% extends 'mainapp/base.html' %}
{% block title %} Подтверждение удаления - MyHabr {% endblock %}
{% block content %}
  <div class="container">
    {% if object.status != "0" %}
      Уверены, что хотите удалить {{ object.title }}?
    {% else %}
      Уверены, что хотите восстановить {{ object.title }}?
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value='{% if object.status != "0" %} удалить {% else %} восстановить {% endif %}'>
    </form>
    <button class="btn btn-success" onclick="location.href='{% url 'blogpost' %}'">
        Отмена
    </button>
  </div>
{% endblock %}

myHabr/mainapp/templates/blogpost/blogpost_form.html
{% extends 'mainapp/base.html' %}
{% block title %} Статья создание - MyHabr {% endblock %}
{% block style %}
    <style>
        select {
            min-width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Создание статьи</h1>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <input type="submit" value="Загрузить статью">
            </form>
        </div>
        <a href="{% url 'blogpost' %}"> Назад </a>
    </div>
{% endblock %}

myHabr/mainapp/templates/blogpost/blogpost_update.html
{% extends 'mainapp/base.html' %}
{% block title %} Статья редактирование - MyHabr {% endblock %}
{% block content %}
    <div class="container">
        <h1>Создание статьи</h1>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-secondary"> СОХРАНИТЬ</button>
            </form>
        </div>
        <a href="#" type="button" onclick="history.back();"> НАЗАД </a>
    </div>
{% endblock %}