myHabr/blogapp/urls.py
from django.urls import path

import blogapp.views as myblogs

app_name = 'blogapp'

urlpatterns = [
    path('', myblogs.MainMyBlogs.as_view(), name='myblogs'),
    path('create/new/', myblogs.MyBlogCreate.as_view(), name='myblog_create'),
    path('<int:pk>/delete/', myblogs.MyBlogDelete.as_view(), name='myblog_delete'),
    path('<int:pk>/edit/', myblogs.MyBlogUpdate.as_view(), name='myblog_update'),
    path('<int:pk>/list/', myblogs.ListHabrOfMyBlog.as_view(), name='habrinmyblog'),
]

myHabr/faq/urls.py
from django.urls import path

from .views import home, single
urlpatterns = [
    path('', home, name='faq'),
    path('<int:id>/', single, name='single'),
]

myHabr/myHabr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blogapp
from blogapp.views import Category, AllBlogsListView
from mainapp import views as mainapp
from mainapp.views import BlogAddCommentLike, BlogAddLike, BlogAddDislike, BlogAddCommentDislike
from feeds import LatestPostsFeed

urlpatterns = [
    path(r'admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
    path('', mainapp.BlogListView.as_view(), name='index'),
    path('faq/', include('faq.urls')),
    path('myblogs/', include('blogapp.urls', namespace='blogapp')),
    path('allblogs/', AllBlogsListView.as_view(), name='allblogs'),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('blog/', mainapp.BlogPostView.as_view(), name='blogpost'),
    path('blog/<int:pk>', mainapp.BlogPostDetail.as_view(), name='blogpost_detail'),
    path('blog/<int:pk>/edit/', mainapp.BlogPostUpdate.as_view(), name='blogpost_update'),
    path('blog/create/new/', mainapp.BlogPostCreate.as_view(), name='blogpost_create'),
    path('blog/<int:pk>/delete/', mainapp.BlogPostDelete.as_view(), name='blogpost_delete'),
    path('blog/<int:pk>/verify/', mainapp.send_under_review, name='send_under_review'),
    path('blog/<int:pk>/private/', mainapp.BlogPostPrivateDetail.as_view(), name='blogpost_detail-private'),
    path('blog/comment/', mainapp.blog_comment, name='blog_comment'),
    path('blog/sub_comment/', mainapp.blog_sub_comment, name='blog_sub_comment'),
    path('blog/comment_edit/', mainapp.blog_comment_edit, name='blog_comment_edit'),
    path('delete_comment/', mainapp.delete_comment, name='delete_comment'),
    path('blog/comment/<int:pk>/like/', BlogAddCommentLike.as_view(), name='comment-like'),
    path('blog/comment/<int:pk>/dislike/', BlogAddCommentDislike.as_view(), name='comment-dislike'),
    path('blog/<int:pk>/like/', BlogAddLike.as_view(), name='like'),
    path('blog/<int:pk>/dislike/', BlogAddDislike.as_view(), name='dislike'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('mark_read/', mainapp.mark_read, name='mark_read'),
    path('message_count/', mainapp.message_count, name='message_count'),
    path('category/<int:pk>/', Category.as_view(), name='category'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('call_moderator/', mainapp.call_moderator, name='cal_moderator'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myHabr/blogapp/models.py
from django.db import models

# Create your models here.


from authapp.models import MyHabrUser


class BlogCategories(models.Model):
    name = models.CharField(max_length=255, verbose_name="название")

    def __str__(self):
        return self.name


class Blogs(models.Model):
    DELETED = "0"
    PUBLISHED = '1'

    BLOG_STATUS = (
        (DELETED, 'блог удален'),
        (PUBLISHED, 'блог опубликован'),

    )

    user = models.ForeignKey(MyHabrUser, on_delete=models.CASCADE)
    category = models.ForeignKey(BlogCategories, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name="название")
    status = models.CharField(max_length=1, choices=BLOG_STATUS, default=PUBLISHED, verbose_name="статус блога")
    image_header = models.ImageField(upload_to='blogposts/', default='default_blogpost.png')

    def __str__(self):
        return self.name

myHabr/blogapp/forms.py
from django import forms
from .models import Blogs


class MyBlogForm(forms.ModelForm):
    """Данная форма работает только с подключенным бутстрапом"""
    class Meta:
        model = Blogs
        fields = ('category', 'name', 'image_header')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'user_id': forms.Select(attrs={'class': 'form-control'}),
            'image_header': forms.FileInput(attrs={'class': 'form-control'}),
        }

myHabr/blogapp/views.py
import logging
from operator import itemgetter

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Blogs
from mainapp.models import BlogPost
from .forms import MyBlogForm

logger = logging.getLogger(__name__)

class AllBlogsListView(ListView):
    """Отображаем список всех блогов для всех пользователей"""
    model = Blogs
    template_name = 'allblogs/allblogs.html'
    paginate_by = 2
    success_url = reverse_lazy('allblogs:allblogs')

    def get_queryset(self, ):
        return Blogs.objects.order_by('name').filter(status__in=Blogs.PUBLISHED)


class ListHabrOfMyBlog(ListView):
    """Просмотр статей в моём блоге"""
    model = BlogPost
    template_name = 'blogapp/habrinmyblog.html'
    paginate_by = 2

    def get_queryset(self):
        return BlogPost.objects.filter(blog=self.kwargs["pk"]).order_by('-create_date')


class MainMyBlogs(ListView):
    model = Blogs
    template_name = 'blogapp/index.html'
    # paginate_by = 1

    def get_queryset(self):
        obj = Blogs.objects.filter(user=self.request.user).order_by('category')
        return obj


class MyBlogCreate(CreateView):
    model = Blogs
    form_class = MyBlogForm
    template_name = "blogapp/myblog_create.html"
    success_url = reverse_lazy('blogapp:myblogs')

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)


class MyBlogDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blogs
    template_name = "blogapp/myblog_delete.html"
    success_url = reverse_lazy("blogapp:myblogs")

    def test_func(self):
        blog = self.get_object()
        if self.request.user.id == blog.user_id:
            return True
        return False


class MyBlogUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blogs
    form_class = MyBlogForm
    template_name = "blogapp/myblog_update.html"
    success_url = reverse_lazy("blogapp:myblogs")

    def test_func(self):
        blog = self.get_object()
        if self.request.user.id == blog.user_id:
            return True
        return False


class Category(ListView):
    model = BlogPost
    template_name = 'mainapp/index.html'
    paginate_by = 3

    def get_queryset(self):
        pk = self.kwargs['pk']
        blog = Blogs.objects.filter(category=pk)
        return BlogPost.objects.order_by('-create_date').filter(status__in=BlogPost.PUBLISHED, blog__in=blog)

    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        blog = Blogs.objects.filter(category=pk)
        blogs = BlogPost.objects.order_by('-create_date').filter(status__in=BlogPost.PUBLISHED, blog__in=blog)
        if self.request.POST.get('pk') == '0':
            new_blogs = [[(blog.likes.count() - blog.dislikes.count()), blog] for blog in blogs]
            new_blogs = sorted(new_blogs, key=itemgetter(0), reverse=True)
            blogs = []
            for i in new_blogs:
                blogs.append(i[1])

        context = {
            'object_list': blogs
        }
        return render(request=request, template_name='mainapp/index.html', context=context)

myHabr/blogapp/templates/blogapp/habrinmyblog.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        {% for post in object_list %}
            <div class="row mb-5">
                <div class="col">
                    <div class="row g-3 p-2">
                        <div class="col" style="background-color: white">
                            <div class="my-1">
                                <b>{{ post.author }}</b>
                                <small>{{ post.create_date }}</small></br>
                                <b>{{ post.title }}</b>
                            </div>
                            <div class="col-md-12 mb-4 element-animate fadeInUp element-animated">
                                <img src="{{ post.image_header.url }}"
                                     alt="Image placeholder"
                                     class="img-fluid"
                                     width="820">
                            </div>
                            <button class="btn btn-outline-white mt-3"><a href="{% url 'blogpost_detail' post.pk %}"
                                                                          class="">Читать дальше</a></button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% include 'mainapp/includes/pagination.html' %}
    </div>
{% endblock %}

myHabr/blogapp/templates/blogapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
  {% block head %}
  <title>Мои блоги </title>
  {% endblock %}

  {% block body %}
      <div class="container">
    <h1>Мои Блоги ({{ request.user.username }}) </h1>
    {% if not object_list %}
      <b>У вас нет Блогов</b>
    {% else %}
            <div class="container">
                <ul>
                    {% for post in object_list %}
                        {% if post.status != "0"  %}

                            <li>
                                <a href="{% url 'blogapp:habrinmyblog' post.pk %}"> {{ post.name }} </a> ( {{ post.category.name }} )<br/>
                                <div class="col-md-12 mb-4 element-animate fadeInUp element-animated">
	                            <img src="{{ post.image_header.url }}"
		                            alt="Image placeholder"
                                    class="img-fluid"
                                    width="820">
                                </div>
                                <a href="{% url 'blogapp:myblog_update' post.pk %}"> Изм. </a>
                                <a href="{% url 'blogapp:myblog_delete' post.pk %}"> Удл. </a><br/>
                            </li>
                        {% endif %}
                    <br/><br/>
                    {% endfor %}
                </ul>
    {% endif %}
                <br/>
                <a href="{% url 'blogapp:myblog_create' %}"> Cоздать </a><br/>
                <a href="{% url 'index' %}"> Назад </a>
            </div>


  {% endblock %}
    </div>
{% endblock %}

myHabr/blogapp/templates/blogapp/myblog_create.html
{% extends 'mainapp/base.html' %}
{% block title %} Блог создание - MyHabr {% endblock %}
{% block content %}
    <div class="container">
    <br/>
    <div class="container">
        <h1>Создание блога</h1>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <input type="submit">
            </form>
        </div>
                <a href="{% url 'blogapp:myblogs' %}"> Назад </a>
    </div>
    </div>
{% endblock %}

myHabr/blogapp/templates/blogapp/myblog_delete.html
{% extends 'mainapp/base.html' %}
{% block title %} Подтверждение удаления - MyHabr {% endblock %}
{% block content %}<br/>
  <div class="container">
    {% if object.status != "0" %}
      Уверены, что хотите удалить блог "{{ object.name }}"?
    {% else %}
      Уверены, что хотите восстановить блог "{{ object.name }}"?
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value='{% if object.status != "0" %} удалить {% else %} восстановить {% endif %}'>
    </form>
    <button class="btn btn-success" onclick="location.href='{% url 'blogpost' %}'">
        Отмена
    </button>
  </div>
{% endblock %}

myHabr/blogapp/templates/blogapp/myblog_update.html
{% extends 'mainapp/base.html' %}
{% block title %} Блог редактирование - MyHabr {% endblock %}
{% block content %}
    <div class="container">
        <h1>Редактирование Блога</h1>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-secondary"> Сохранить</button>
            </form>
        </div>
        <a href="{% url 'blogapp:myblogs' %}"> Назад </a>
    </div>
{% endblock %}