myHabr/faq/urls.py
from django.urls import path

from .views import home, single
urlpatterns = [
    path('', home, name='faq'),
    path('<int:id>/', single, name='single'),
]

myHabr/myHabr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blogapp
from blogapp.views import Category, AllBlogsListView
from mainapp import views as mainapp
from mainapp.views import BlogAddCommentLike, BlogAddLike, BlogAddDislike, BlogAddCommentDislike
from feeds import LatestPostsFeed

urlpatterns = [
    path(r'admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
    path('', mainapp.BlogListView.as_view(), name='index'),
    path('faq/', include('faq.urls')),
    path('myblogs/', include('blogapp.urls', namespace='blogapp')),
    path('allblogs/', AllBlogsListView.as_view(), name='allblogs'),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('blog/', mainapp.BlogPostView.as_view(), name='blogpost'),
    path('blog/<int:pk>', mainapp.BlogPostDetail.as_view(), name='blogpost_detail'),
    path('blog/<int:pk>/edit/', mainapp.BlogPostUpdate.as_view(), name='blogpost_update'),
    path('blog/create/new/', mainapp.BlogPostCreate.as_view(), name='blogpost_create'),
    path('blog/<int:pk>/delete/', mainapp.BlogPostDelete.as_view(), name='blogpost_delete'),
    path('blog/<int:pk>/verify/', mainapp.send_under_review, name='send_under_review'),
    path('blog/<int:pk>/private/', mainapp.BlogPostPrivateDetail.as_view(), name='blogpost_detail-private'),
    path('blog/comment/', mainapp.blog_comment, name='blog_comment'),
    path('blog/sub_comment/', mainapp.blog_sub_comment, name='blog_sub_comment'),
    path('blog/comment_edit/', mainapp.blog_comment_edit, name='blog_comment_edit'),
    path('delete_comment/', mainapp.delete_comment, name='delete_comment'),
    path('blog/comment/<int:pk>/like/', BlogAddCommentLike.as_view(), name='comment-like'),
    path('blog/comment/<int:pk>/dislike/', BlogAddCommentDislike.as_view(), name='comment-dislike'),
    path('blog/<int:pk>/like/', BlogAddLike.as_view(), name='like'),
    path('blog/<int:pk>/dislike/', BlogAddDislike.as_view(), name='dislike'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('notify/', mainapp.NotifyListView.as_view(), name='notify'),
    path('mark_read/', mainapp.mark_read, name='mark_read'),
    path('message_count/', mainapp.message_count, name='message_count'),
    path('category/<int:pk>/', Category.as_view(), name='category'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('call_moderator/', mainapp.call_moderator, name='cal_moderator'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myHabr/profiles/urls.py
from django.urls import path
from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('<int:id_profile>/<int:user>/', views.profile, name='profile'),
    # path('create_profile/<int:id>/', views.create_profile, name='create'),
    path('create_update_profile/<int:id>/', views.update_profile, name='update'),
    # path('like/<int:id>/', views.like, name='like')
    path('like/<int:who_id>/<int:whom_id>/', views.profile_like, name='like'),
    path('dislike/<int:who_id>/<int:whom_id>/', views.profile_dislike, name='dislike'),
]

myHabr/profiles/models.py
from django.db import models
from authapp import models as mod


# Create your models here.

class Profile(models.Model):
    # Связываем user_id с таблицей MyHabrUser с момошью связи 1 к 1.
    user_id = models.OneToOneField(to=mod.MyHabrUser, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=50, null=False, blank=True, default='')
    last_name = models.CharField(max_length=50, null=False, blank=True, default='')
    age = models.PositiveSmallIntegerField(default=18)
    text = models.TextField(null=False, blank=True, default='')
    update_profile = models.BooleanField(default=False, editable=False)
    image = models.ImageField(upload_to='profile_images', default='default_photo_profile.png')

    likes = models.IntegerField(default=0, verbose_name='Количество лайков', editable=False)
    dislikes = models.IntegerField(default=0, verbose_name='Количество дизлайков', editable=False)

class LikeProfile(models.Model):
    WHO_LIKE = (
        ('N', 'нет лайка'),
        ('L', 'лайк'),
        ('D', 'Дизлайк'),
    )

    who_did = models.ForeignKey(to=mod.MyHabrUser, on_delete=models.CASCADE, verbose_name='Кто лайкнул', related_name='who_did', blank=True)
    to_whom_did = models.ForeignKey(to=mod.MyHabrUser, on_delete=models.CASCADE, verbose_name='Кого лайкнули', related_name='to_whom_did', blank=True)
    how = models.CharField(choices=WHO_LIKE, default='N', verbose_name='Как лайкнули', max_length=1)

myHabr/profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=50, label='Имя: ', required=False)
    last_name = forms.CharField(max_length=50, label='Фамилия: ', required=False)
    age = forms.IntegerField(max_value=150, label='Возраст: ', required=False)
    text = forms.CharField(widget=forms.Textarea, label='О себе: ', required=False)
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    # def form_initial(self, id):
    #     # Пытаюсь в цикле поставить значение элемента формы initial из БД НЕ ПОЛУЧАЕТСЯ
    #     obj = Profile.objects.in_bulk([id])
    #
    #     for k, v in self.fields.items():
    #         for id_ob in obj:
    #             self.fields[k].initial = obj[id_ob][k]

myHabr/profiles/views.py
import sys

sys.path.append('..')

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Profile, LikeProfile
from .forms import ProfileForm
from authapp.models import MyHabrUser
from django.db.models import F

# Create your views here.

def profile(request, id_profile, user):
    if user:
        # Получаем объект пользователя который заходим в профиль. И его профиль
        reg_user = MyHabrUser.objects.get(id=user)
        reg_profile = Profile.objects.get(user_id=reg_user)

        # Получаем объект пользователя к которому заходим в профиль.
        user = MyHabrUser.objects.get(id=id_profile)
        # Получаем из БД данные профиля
        profile = Profile.objects.get(user_id=user)

        # Условие если хоть какие то данные заполнены то мы передаем заполненные данные
        # Если имеется имя или фамилия
        if profile.first_name or profile.last_name:
            # Создаем переменную name, которая отразит в тэге title данные.
            name = f'{profile.first_name} {profile.last_name}'
        else:
            # Если таких данных нет то передает False
            name = False

        # Находим делал ли лайк зарег профиль профилю к которому зашел
        try:
            like = LikeProfile.objects.get(who_did=reg_user, to_whom_did=user)

        except:
            true_like = False
            true_dislike = False
        # Если зарег пользователь лайкал профиль автора то мы определяем был ли это лайк или нет
        else:
            if like.how == 'L':
                true_like = True
            else:
                true_like = False
            if like.how == 'D':
                true_dislike = True
            else:
                true_dislike = False

        guest = False
        profile_form_url = profile.image
        context = {
            'profile': profile, 'name': name, 'profile_id': user, 'reg_profile': reg_profile, 'true_like': true_like, 'true_dislike': true_dislike, 'guest': guest, 'profile_form_url': profile_form_url,

        }

        return render(request=request, template_name='profile.html', context=context)

    else:
        # Получаем объект пользователя к которому заходим в профиль.
        user = MyHabrUser.objects.get(id=id_profile)
        # Получаем из БД данные профиля
        profile = Profile.objects.get(user_id=user)

        # Условие если хоть какие то данные заполнены то мы передаем заполненные данные
        # Если имеется имя или фамилия
        if profile.first_name or profile.last_name:
            # Создаем переменную name, которая отразит в тэге title данные.
            name = f'{profile.first_name} {profile.last_name}'
        else:
            # Если таких данных нет то передает False
            name = False

        guest = True
        profile_form_url = profile.image
        context = {
            'profile': profile, 'name': name, 'profile_id': user, 'guest': guest, 'profile_form_url': profile_form_url,
        }
        return render(request=request, template_name='profile.html', context=context)

def create_profile(request, id):
    if request.method == 'POST':
        new_profile_for_user = MyHabrUser.objects.get(id=id)

        # При пост запросе получвем данные из формы
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        text = request.POST.get('text')

        # Применяем данные к объекту
        new_profile = Profile(user_id=new_profile_for_user, first_name=first_name,
                              last_name=last_name, age=age, text=text)
        new_profile.save()

    else:
        return render(request=request, template_name='create_update_profile.html', )


def update_profile(request, id):
    # Получаем объект пользователя
    user = MyHabrUser.objects.get(id=id)
    # Получаем из БД данные профиля
    profile = Profile.objects.get(user_id=user)

    # Условие если хоть какие то данные заполнены то мы передаем заполненные данные
    # Если имеется имя или фамилия
    if profile.first_name or profile.last_name:
        # Создаем переменную name, которая отразит в тэге title данные.
        name = f'{profile.first_name} {profile.last_name}'
    else:
        # Если таких данных нет то передает False
        name = False

    if request.method == 'POST':
        # При пост запросе получвем данные из формы
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        text = request.POST.get('text')

        # Применяем данные к объекту
        profile.first_name = first_name
        profile.last_name = last_name
        profile.age = age
        profile.text = text
        if request.FILES:
            profile.image = request.FILES['image']
        profile.save()

        # Возвращаемся на страницу пользователя
        return HttpResponseRedirect(reverse('profiles:update', args=[id]))

    else:
        # Если имеем Гет запрос загружаем форму
        profile_form = ProfileForm()
        # Устанавливаем имеющиеся значенрия из каждой формы
        profile_form['first_name'].initial = profile.first_name
        profile_form['last_name'].initial = profile.last_name
        profile_form['age'].initial = profile.age
        profile_form['text'].initial = profile.text
        profile_form['image'].initial = profile.image
        context = {
            'profile_form': profile_form,
            'profile_form_url': profile.image
        }
        return render(request=request, template_name='create_update_profile.html', context=context)


def profile_like(request, who_id, whom_id):
    # Получаем объект пользователя кому ставят лайк
    user_whom_id = MyHabrUser.objects.get(id=whom_id)
    # Получаем объект пользователя кто ставит лайк
    user_who_id = MyHabrUser.objects.get(id=who_id)

    # Получаем из БД данные профиля
    profile = Profile.objects.get(user_id=user_whom_id)
    profile_like = profile.likes
    profile_dislike = profile.dislikes

    try:
        like = LikeProfile.objects.get(who_did=user_who_id, to_whom_did=user_whom_id)
    except:
        like = LikeProfile.objects.create(who_did=user_who_id, to_whom_did=user_whom_id, how='N')
    # Если все же пользователь делал лайк автору то мы определяем что он до этого сделал И меняем количество лайков соответственно тому что нажал пользователь.
    if like.how == 'L':

        if profile_like - 1 < 0:
            profile.likes = 0
        else:
            profile.likes = profile_like - 1
        profile.save()

        like.how = 'N'
        like.save()
        print(f'{like.how} сейчас такой статус из L')
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))

    if like.how == 'D':

        if profile_dislike - 1 < 0:
            profile.dislikes = 0
        else:
            profile.dislikes = profile_dislike - 1
        profile.likes = profile.likes + 1
        profile.save()

        like.how = 'L'
        like.save()
        print(f'{like.how} сейчас такой статус из D')
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))
    if like.how == 'N':

        profile.likes = profile_like + 1
        profile.save()

        like.how = 'L'
        like.save()
        print(f'{like.how} сейчас такой статус из Т')
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))

def profile_dislike(request, who_id, whom_id):
    # Получаем объект пользователя кому ставят лайк
    user_whom_id = MyHabrUser.objects.get(id=whom_id)
    # Получаем объект пользователя кто ставит лайк
    user_who_id = MyHabrUser.objects.get(id=who_id)

    # Получаем из БД данные профиля
    profile = Profile.objects.get(user_id=user_whom_id)
    profile_like = profile.likes
    profile_dislike = profile.dislikes

    try:
        like = LikeProfile.objects.get(who_did=user_who_id, to_whom_did=user_whom_id)
    except:
        like = LikeProfile.objects.create(who_did=user_who_id, to_whom_did=user_whom_id, how='N')
    # Если все же пользователь делал лайк автору то мы определяем что он до этого сделал И меняем количество лайков соответственно тому что нажал пользователь.
    if like.how == 'L':

        if profile_like - 1 < 0:
            profile.likes = 0
        else:
            profile.likes = profile_like - 1
        profile.dislikes = profile_dislike + 1
        profile.save()

        like.how = 'D'
        like.save()
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))

    if like.how == 'D':

        if profile_dislike - 1 < 0:
            profile.dislikes = 0
        else:
            profile.dislikes = profile_dislike - 1
        profile.save()

        like.how = 'N'
        like.save()
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))
    if like.how == 'N':

        profile.dislikes = profile_dislike + 1
        profile.save()

        like.how = 'D'
        like.save()
        return HttpResponseRedirect(reverse('profiles:profile', args=[whom_id, who_id]))

myHabr/profiles/templates/create_update_profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
{% if name %}
<title>Внесите данные о {{ name }}</title>
{% else %}
<title>Внесите данные</title>
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    {% if empty_keys %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Не заполнены следующие поля:</strong> {{empty_keys}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="text-center">
                <h1>Информация о профиле</h1>
                <div class="col-md-12 mb-4 element-animate fadeInUp element-animated">
                    <img src="{{ profile_form_url.url }}"
                         alt="Image Placeholder"
                         width="640"
                         height="480"
                         class="img-fluid rounded-circle">
                </div>
                <br><br>
                <h2> {{ profile_form.first_name.value}} {{ profile_form.last_name.value }}</h2>
            </div>
        </div>
    </div>
    <div class="row blog-entries">
        <div class="col-md-12 col-lg-12 main-content">
            <form action="{% url 'profiles:update' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-md-7 mx-auto">
                    <tr>
                        <div class="text-center">
                            <th>
                                <label>Загрузить новое фото (4:3)</label>
                            </th>
                        </div>
                        <td>
                            <input type="file"
                                   class="form-control"
                                   name="{{profile_form.image.name}}"
                                   accept="image/*"
                                   id="{{profile_form.id_image.label}}">
                        </td>
                    </tr>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label for="{{profile_form.id_first_name.label}}">Имя</label></th>
                            <td><input type="text"
                                       class="form-control "
                                       name="{{profile_form.first_name.name}}"
                                       value="{{profile_form.first_name.value}}"
                                       maxlength="50"
                                       id="{{profile_form.id_first_name.label}}"></td>
                        </tr>
                    </div>
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label for="{{profile_form.last_name.label}}">Фамилия</label></th>
                            <td><input type="text"
                                       class="form-control "
                                       name="{{profile_form.last_name.name}}"
                                       value="{{profile_form.last_name.value}}"
                                       maxlength="50"
                                       id="{{profile_form.last_name.label}}"></td>
                        </tr>
                    </div>
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label for="{{profile_form.age.label}}">Возраст</label></th>
                            <td><input type="number"
                                       class="form-control "
                                       name="{{profile_form.age.name}}"
                                       value="{{profile_form.age.value}}"
                                       maxlength="50"
                                       id="{{profile_form.age.label}}"></td>
                        </tr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 form-group">
                        <tr>
                            <th><label for="{{profile_form.id_text.label}}">О себе</label></th>
                            <td><textarea name="{{profile_form.text.name}}"
                                          class="form-control "
                                          cols="40"
                                          rows="10"
                                          id="{{profile_form.id_text.label}}">{{profile_form.text.value}}</textarea>
                            </td>
                        </tr>
                        <br>
                        <input class="btn btn-success" type="submit" value="Сохранить изменения профиля">
                    </div>
                </div>
            </form>
            <div class="col-md-6 form-group">
                <a href="{% url 'blogpost_create' %}" class="btn-group-toggle">Создать новую статью</a>
            </div>
            <div class="col-md-6 form-group">
                <a href="{% url 'blogpost' %}" class="btn-group-toggle">Посмотреть мои статьи</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myHabr/profiles/templates/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
{% if name %}
<title>Информация о профиле {{ name }}</title>
{% else %}
<title>Информация о профиле</title>
{% endif %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="text-center">
                <h1>Информация о профиле</h1>
                <h2>{{ name }}</h2>
                    {% if user.id != profile_id.id and guest == False %}
                    {% if guest %}
                    <form method="POST" action="{% url 'profiles:like' 0 profile_id.id %}" class="like-form mb-0" id="">
                    {% else %}
                    <form method="POST" action="{% url 'profiles:like' user.id profile_id.id %}" class="like-form mb-0" id="">
                    {% endif %}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="">
                    <button class="btn btn-light" type="submit">
                        <div class="text-success">
                            {% if true_like %}
                                <div class="mr-2">
                                    <i class="fa fa-thumbs-up like-{{ profile_id.id }}">{{ profile.likes }}</i>
                                </div>
                            {% else %}
                                <div class="mr-2">
                                    <i class="fa fa-thumbs-up like-{{ profile_id.id }}">{{ profile.likes }}</i>
                                </div>
                            {% endif %}
                        </div>
                    </button>
                    </form>
                    {% if guest %}
                    <form method="POST" action="{% url 'profiles:dislike' 0 profile_id.id %}" class="dislike-form mb-0" id="">
                    {% else %}
                    <form method="POST" action="{% url 'profiles:dislike' user.id profile_id.id %}" class="dislike-form mb-0" id="">
                    {% endif %}
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <button class="btn btn-light" type="submit">
                            <div class="text-danger">
                                {% if true_dislike %}
                                    <div class="mr-0">
                                        <i class="fa fa-thumbs-down dislike-{{ profile_id.id }}">{{ profile.dislikes }}</i>
                                    </div>
                                {% else %}
                                    <div class="mr-2">
                                        <i class="fa fa-thumbs-down dislike-{{ profile_id.id }}">{{ profile.dislikes }}</i>
                                    </div>
                                {% endif %}
                            </div>
                        </button>
                    </form>
                {% else %}
                    Сколько лайков {{ profile.likes }} Сколько дислайков {{ profile.dislikes }}
                {% endif %}
                    <h5>
                        <div class="col-md-12 mb-4 element-animate fadeInUp element-animated">
                            <img src="{{ profile.image.url }}"
                                 alt="Image Placeholder"
                                 width="640"
                                 height="480"
                                 class="img-fluid rounded-circle">
                        </div>
                    </h5>
            </div>
        </div>
    </div>
    <div class="row blog-entries">
        <div class="col-md-12 col-lg-12 main-content">
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label>Имя</label></th>
                            <td><input type="text" readonly
                                       class="form-control "
                                       name="{{profile.first_name}}"
                                       value="{{profile.first_name}}">
                            </td>
                        </tr>
                    </div>
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label>Фамилия</label></th>
                            <td><input type="text" readonly
                                       class="form-control "
                                       name="{{profile.last_name}}"
                                       value="{{profile.last_name}}">
                            </td>
                        </tr>
                    </div>
                    <div class="col-md-4 form-group">
                        <tr>
                            <th><label>Возраст</label></th>
                            <td><input type="number" readonly
                                       class="form-control "
                                       name="{{profile.age}}"
                                       value="{{profile.age}}">
                            </td>
                        </tr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 form-group">
                        <tr>
                            <th><label>О себе</label></th>
                            <td><textarea readonly
                                          class="form-control"
                                          cols="40"
                                          rows="10">{{profile.text}}</textarea>
                            </td>
                        </tr>
                    </div>
                </div>
            </form>
            {% if user.id == profile_id.id %}
            <div class="col-md-6 form-group">
                <a href="{% url 'profiles:update' user.id %}" class="btn-group-toggle">Редактировать профиль</a>
            </div>
            <div class="col-md-6 form-group">
                <a href="{% url 'blogpost_create' %}" class="btn-group-toggle">Написать статью</a>
            </div>
            <div class="col-md-6 form-group">
                <a href="{% url 'blogpost' %}" class="btn-group-toggle">Все мои статьи</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}